services:
  api:
    build: ./apps/api
    container_name: task-flow-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always

  frontend:
    build: ./apps/frontend
    container_name: task-flow-frontend
    ports:
      - "80:80"
    depends_on:
      - api
    restart: always
